import type { Metadata } from "next";
import { Fredoka } from "next/font/google";
import "../globals.css";
import AdminLayout from "../components/admin-components/AdminLayout";

const fredoka = Fredoka({ 
  weight: ['300', '400', '500', '600', '700'],
  subsets: ['latin'],
  variable: '--font-fredoka',
  display: 'block'
})


export const metadata: Metadata = {
  title: "PAUD Cahya Indria",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <AdminLayout>{children}</AdminLayout>
  );
}