import type { Metadata } from "next";
import { Fredoka } from "next/font/google";
import { AuthProvider } from '@/lib/AuthContext';
import "./globals.css";

const fredoka = Fredoka({ 
  weight: ['300', '400', '500', '600', '700'],
  subsets: ['latin'],
  variable: '--font-fredoka',
  display: 'block'
})

export const metadata: Metadata = {
  title: "PAUD Cahya Indria",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${fredoka.variable} antialiased`}>
        <AuthProvider>
          {children}
        </AuthProvider>
      </body>
    </html>
  );
}